# cht package

name: cht
parent: default

global_vars:
  - name: query
    type: shell
    params:
      cmd: 'echo {{command}} | sed -r "s/ +/%20/g"'
  - name: url
    type: echo
    params:
      echo: 'https://cht.sh/{{query}}'

matches:
  - regex: ":cht/(?P<command>.*)/"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'curl "{{url}}?QT&style=bw"'

  - regex: ":vcht/(?P<command>.*)/"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'curl "{{url}}?qT&style=bw"'
